package domain;

public enum Clases {
	GUERRERO, GuerreroACROBATA, PALADIN, PaladinOSCURO, MAESTROdeARMAS, 
	TECNICISTA, EXPLORADOR, TAO, SOMBRA, ASESINO, LADRON, HECHICERO, WARLOCK, 
	ILUSIONISTA, HechiceroMENTALISTA, CONJURADOR, GuerreroCONJURADOR, 
	MENTALISTA, GuerreroMENTALISTA, NOVEL
	
}
